// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFdVyo99nif7rYmQCwUBMrn_D3CZcmBlw',
    appId: '1:958196033224:web:a8df4ad6b29cdae688e7fd',
    messagingSenderId: '958196033224',
    projectId: 'chatdesktop-fcbd1',
    authDomain: 'chatdesktop-fcbd1.firebaseapp.com',
    storageBucket: 'chatdesktop-fcbd1.appspot.com',
    measurementId: 'G-QV6FC2WVLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzy_iWM7YiQvQNhxyJZLQ4lpWnmx1Rg84',
    appId: '1:958196033224:android:d75a014877ee546a88e7fd',
    messagingSenderId: '958196033224',
    projectId: 'chatdesktop-fcbd1',
    storageBucket: 'chatdesktop-fcbd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB79RwxUZCzoPPqKWBbzTPgTa5mKkUA_Ak',
    appId: '1:958196033224:ios:8f7b6b75f6a860ec88e7fd',
    messagingSenderId: '958196033224',
    projectId: 'chatdesktop-fcbd1',
    storageBucket: 'chatdesktop-fcbd1.appspot.com',
    androidClientId: '958196033224-bdoocbhdfj7ern83laj30ce1pdb1u3bl.apps.googleusercontent.com',
    iosClientId: '958196033224-nrn1cgomrhprr51bjmpddei8ho8n18re.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication5',
  );
}
